PRODUCT_PACKAGES += \
    FontAlconicaOverlay \
    FontAmaranteOverlay \
    FontArbutusOverlay \
    FontAvantGardeGothOverlay \
    FontAvantGardeGothBDOverlay \
    FontBariolOverlay \
    FontBerlinSansOverlay \
    FontCagliostroOverlay \
    FontCaviarDreamsOverlay \
    FontCircularStdOverlay \
    FontComfortaaOverlay \
    FontComicSansOverlay \
    FontCoolstoryOverlay \
    FontGoogleSansOverlay \
    FontexotwoOverlay \
    FontFiraSansOverlay \
    FontFrutigerNeueOverlay \
    FontIgraSansOverlay \
    FontInterOverlay \
    FontLatoOverlay \
    FontLGSmartGothicOverlay \
    FontLinotteOverlay \
    FontMagistralOverlay \
    FontMilanPro11Overlay \
    FontMilanPro12Overlay \
    FontMindustryOverlay \
    FontOpenSansOverlay \
    FontOxaniumOverlay \
    FontRobotoSerifOverlay \
    FontRoganOverlay \
    FontRosemaryOverlay \
    FontRubikOverlay \
    FontSamsungOneOverlay \
    FontSamsungSansOverlay \
    FontsfboldOverlay \
    FontSFProArabicOverlay \
    FontsfproOverlay \
    FontsfprotextOverlay \
    FontSignikaOverlay \
    FontSlate_for_OnePlusOverlay \
    FontSnigletOverlay \
    FontSonySketchOverlay \
    FontStoropiaOverlay \
    FontSuperscienceOverlay \
    FontSurferOverlay \
    FontUbuntuOverlay \
    FontUssrStencilOverlay \
