BAIKALOS_BRANCH=t

# BAIKALOS RELEASE VERSION
BAIKALOS_VERSION_MAJOR = 18
BAIKALOS_VERSION_MINOR = 0
BAIKALOS_VERSION_MAINTENANCE = 0

PRODUCT_VERSION_MAJOR := $(BAIKALOS_VERSION_MAJOR)
PRODUCT_VERSION_MINOR := $(BAIKALOS_VERSION_MINOR)
PRODUCT_VERSION_MAINTENANCE := $(BAIKALOS_VERSION_MAINTENANCE)

VERSION := $(BAIKALOS_VERSION_MAJOR).$(BAIKALOS_VERSION_MINOR)

ifndef BAIKALOS_BUILDTYPE
    ifdef RELEASE_TYPE
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^BAIKALOS_||g')
        BAIKALOS_BUILDTYPE := $(RELEASE_TYPE)
    else
        BAIKALOS_BUILDTYPE := UNOFFICIAL
    endif
endif

ifdef BAIKALOS_BUILDTYPE
    ifeq ($(BAIKALOS_BUILDTYPE), NIGHTLY)
        BAIKALOS_VERSION := $(TARGET_PRODUCT)_$(BAIKALOS_BRANCH)-$(VERSION)-NIGHTLY-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(BAIKALOS_BUILDTYPE), WEEKLY)
       BAIKALOS_VERSION := $(TARGET_PRODUCT)_$(BAIKALOS_BRANCH)-$(VERSION)-WEEKLY-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(BAIKALOS_BUILDTYPE), EXPERIMENTAL)
        BAIKALOS_VERSION := $(TARGET_PRODUCT)_$(BAIKALOS_BRANCH)-$(VERSION)-EXPERIMENTAL-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(BAIKALOS_BUILDTYPE), UNOFFICIAL)
        BAIKALOS_VERSION := $(TARGET_PRODUCT)_$(BAIKALOS_BRANCH)-$(VERSION)-UNOFFICIAL-$(shell date -u +%Y%m%d)
    endif
else
#We reset back to UNOFFICIAL
        BAIKALOS_VERSION := $(TARGET_PRODUCT)_$(BAIKALOS_BRANCH)-$(VERSION)-UNOFFICIAL-$(shell date -u +%Y%m%d)
endif
